---
title: "A collection of Jupyter Notebooks"
---

:::{.callout-note}  
Last update: 21 Jan 2024

- These pages are draft copies and only half baked.
- Many sections are still under construction.
- Only preliminary files have been posted to github. 
- Spelling and grammar checks have not been completed.
- The pages are posted for testing only.  
:::  

# Introduction
This site provides a place to host a few of my JupyterLab notebooks. The [JupyterLab notebooks](https://jupyterlab.readthedocs.io/en/latest/) use the [SymPy](https://www.sympy.org/), [NumPy](https://numpy.org/), [SciPy](https://scipy.org/), [Pandas](https://pandas.pydata.org/) and the [Python](https://www.python.org/) programming language libraries to analyize various topics. Jupyter Notebooks are used for a varity of programming projects. The notebooks combine code and narrative in the same ducument. Within a jupyter notebook there are three types of cells, code cells, markdown cells and raw cells. The code cells contain the python code, the markdown cells contain text that can be formated with markdown. The combination of code cells mingled with mardown cells provides a convient and powerful way to build a report containtaining narrative and the results of calculations. 

As new notebooks are completed a hyperlink will be added. Topics in the outlines below are ideas for future notebooks.

## [Electrical engineering](https://en.wikipedia.org/wiki/Electrical_engineering)
The following notebooks cover various topics in electrical engineering. Electrical engineering is an engineering discipline concerned with electricity, electronics and electromagnetism. My intrest is in circuits and systems, which covers theory, analysis, design, practical implementations of circuits and the application of circuit techniques to systems and to signal processing. 

### Circuit Analysis

#### [Symbolic Modified Nodal Analysis using Python](https://tiburonboy.github.io/Symbolic-Modified-Nodal-Analysis-using-Python/)
The link above is to the online version of my book: Symbolic Modified Nodal Analysis using Python. Symbolic circuit analysis is a circuit analysis method that derives network equations with the circuit elements represented by symbols.

#### [Source free series circuit](Source free series circuit.ipynb)
In this notebook, the Python modules SymPy and SciPy are used to solve for currents and voltages in a series R, L and C circuit from the characteristic differential equation. A source free series RLC circuit consists of a resistor, capacitor and inductor connected in series with some initial energy stored either in the inductor, capacitor or both. Since the circuit is a single loop, the current flowing around the loop is the same current in each component. Both parallel and series connected circuits are usually presented in electrical circuit analysis classes. The two textbooks I used while in college presented the parallel connected circuit in some detail then kind of glossed over the series connect circuit since it is the dual of the other. The circuit to be analyzed is shown below and was drawn using EasyEDA, the link to the schematic is here. 

### Filter synthesis

#### [SciPy analog filter design](SciPy analog filter design.ipynb)  
This notebook describes the use of filter functions in the [SciPy](https://docs.scipy.org/doc/scipy/reference/signal.html) library which can be used to design analog filters. Filters are one of the basic building blocks of signal processing. In general terms, filters used for signal processing can be divided into two groups, analog and digital filters. Analog filters, the topic of this notebook, are filters which can be described with linear differential equations and implemented in circuits which operate on continuously varying signals. A digital filter is a system that performs operations on a sampled, discrete-time signal with numerical operations. The first part of this notebook uses SciPy functions to calculate analog filter polynomials based on the classical [Butterworth](https://en.wikipedia.org/wiki/Butterworth_filter), [Chebyshev](https://en.wikipedia.org/wiki/Chebyshev_filter), [Elliptic](https://en.wikipedia.org/wiki/Elliptic_filter) and [Bessel](https://en.wikipedia.org/wiki/Bessel_filter) filters. The last section of this notebook walks through a Butterworth filter design and Cauer synthesis of an LC ladder type filter. 

Future topics

- Polynimial implementations
- Active implementations
  - State variable filter design  
  - Bi-Quad LP, HP, BP, BR  
  - Sallen Key active filter
- Crystal filters
- Helical filters
- Wave guide filters

### [Analog Circuits](https://en.wikipedia.org/wiki/Electronic_circuit)
Analog electronic circuits are those in which current or voltage vary continuously with time to correspond to the information being represented. The basic components of analog circuits are wires, resistors, capacitors, inductors, diodes, and transistors.

Future topics

- semiconductors
- Diodes
- Transistors
- Amplifiers
- Wave forming circuits
- Power electronics
- Analog computing
- Vacuum tube models for SPICE

### Electric Machines & Electromechanics

#### [Overshot waterwheel hydroelectric power system analysis](Overshot waterwheel hydroelectric power system analysis.ipynb)
This notebook examines the construction of a small hydroelectric system built by [Michael Loftis](https://www.youtube.com/c/LoftisPartyofSix/about), a YouTuber, real estate and insurance broker, who had a hydro system built for his off-grid cabin on 50 acres in the Ozark Mountains. The cabin and hydro system are unique and look really interesting. The cabin is available for rent as an AirBnB and is located in Thornfield, Missouri. The cabin is now advertised as having some solar panels with a gas powered generator to supplement the solar. Michael's hydroelectric project looked really interesting and I was curious about the technical details. In the YouTube videos, [Did we MAKE HYDRO POWER Using Our Waterwheel for Self Reliant Off Grid Living?](https://www.youtube.com/watch?v=VFQQI96CMK8) and [Possible Hydro Power Solutions for our Off Grid Cabin? A BIG THANKS TO YOU!!](https://www.youtube.com/watch?v=iMqMIJGlrdc), he discusses the status of the system. I was disappointed to hear that his system wasn't working, because at first glance it looked very impressive. I decided to learn a little about small hydroelectric systems and document in this notebook what I've learned.

#### [Lake District Overshot Waterwheel Project Review and Analysis](Lake District Overshot Waterwheel Project.ipynb)
This notebook examines the design of a small hydroelectric water wheel built by [Kris Harbour Natural Building](https://www.krisharbour.co.uk/). The water wheel is a 2.1 meter diameter wheel and he expected to generate between  1.5 and 1.7 kW. The project is documented in four YouTube videos, links are here: [Part 1](https://www.youtube.com/watch?v=7l5xxIGiW7o), [Part 2](https://www.youtube.com/watch?v=PvgeSJKlNUs), [Part 3](https://www.youtube.com/watch?v=DInwut0DzTQ), [Part 4](https://www.youtube.com/watch?v=WPICp3c_qIQ) and [Part 5](https://www.youtube.com/watch?v=RWTgMWRc2W4). The videos provide some technical details, but not enough to satisfy me. My JupyterLab notebook will cover the project description, the water wheel design, generator, flume, inverter and other topics he did not address such as instrumentation, safety, maintenance, reliability and economics. (this is a work in progress)

Future topics

- electric power, motors, magnetics  
- Inductor and transformer design  
- Electric propulsion  

### Heat transfer
- Heat sink calculations for audio power amplifier <!--- : TPA6021A4 with 20-pin DIP anodized heat sink (Aavid Thermalloy 580400B00000, Digi-Key HS181-ND) ---> 
- Cooling of a PCB in a box (example 15-12)
- Cooling of a sealed box (example 15-10)

### Radio and RF design
- scikit-rf  
- signals and spectra, modulation and coding  
- topics in microwave engineering  
- Smith chart plots  
- antenna design  
- antenna temperature  
- receiver design, analog FE for SDR  
- Link Analysis  
  - starlink example (LEO)  
  - Direct to cellphone satellite service  
- Hydrogen line receiver  
  - H1 line signal strength    
  - basic design and feasibility  
  - antenna design, horn, other   
  - receiver design  
  - filter design  
  - mapping the sky  

### [Information security](https://en.wikipedia.org/wiki/Information_security)

#### [Password card](password_card.ipynb)
This notebook describes the use of a password card and the Python code that generates the password card. The password card is a grid of random letters, numbers and special characters that provides a convenient aid to generate and remember long and complex passwords. A basic description of the password card and instructions are provided along with the Python code used to generate the password card. A security analysis and an analysis of alternatives is provided. 

- Diceware  
- Encrypt text for SMS  

### Electromagnetics
- coil design

### Signal processing
- Fourier transforms
- Discrete Fourier transforms
- Windows
- Filters

### Circuit Python
- A description is [here](https://learn.adafruit.com/welcome-to-circuitpython) and [here](https://circuitpython.org/)
- A list of hardware supported is [here](https://circuitpython.org/downloads?sort-by=date-desc)

## [Civil engineering](https://en.wikipedia.org/wiki/Civil_engineering)
- Design of footings
- Capacity of foudations

## [Mechanical engineering](https://en.wikipedia.org/wiki/Mechanical_engineering)
- Two point supported beam
- Cantilever beam
- Thermal effictiveness of fins
- Fluid flow in pipes
- Area moment of inertia
- Helical spring
- atmospheric water extraction
- canaon ball balistics
- Trombe wall
- Boiling eggs (example 4-3)

## [Engineering economics](https://en.wikipedia.org/wiki/Engineering_economics)
- Value analysis
- Linear programming
- Critical path economy
- Interest and money - time relationships
- Depreciation and valuation
- Capital budgeting
- Risk, uncertainty, and sensitivity analysis
- Fixed, incremental, and sunk costs
- Replacement studies
- Minimum cost formulas
- Various economic studies in relation to both public and private ventures

## [Engineering mathmatics](https://en.wikipedia.org/wiki/Engineering_mathematics)
- Differential equations
- Linear differential equations
- Simutaneous linear differential equations
- Fourier series and integrals
- Laplace transform
- Partial differential equations
- Bessel functions
- Functions of a complex variable
- Integration in the complex plane
- Theory of reidues
- Conformal mapping
- Vector analysis
- Taylor series
- Gamma and Beta functions
- Numerical soultion of equations


